---
  - name: "Ansible local test"
    hosts: all
    remote_user: root
    become: yes
    become_method: sudo
    tasks:

    # - name: "Create the production folder"
    #   shell: "mkdir -p /home/lector/Cloud-API_Deployment/production"

    # - name: "Create a simple file in production"
    #   shell: "touch /home/lector/Cloud-API_Deployment/production/production.html"

    # - name: "Add content to file"
    #   copy: content="<h1>Production Server</h1>" dest="/home/lector/Cloud-API_Deployment/production/production.html"

    - name: Install pip
      apt: name=python-pip state=present

    - name: Install docker-py
      pip: name=docker-py

    - name: Build docker image
      docker_image:
        name: ov-cloud-api
        path: ../Cloud-API
        state: build

    - name: Run the container
      docker_container:
        image: ov-cloud-api:latest
        path: ../Cloud-API
        state: running

    - name: Check if the container is running
      shell: docker ps