---
  - name: "Ansible local test"
    hosts: all
    remote_user: root
    become: yes
    become_method: sudo
    tasks:

    # - name: "Create the production folder"
    #   shell: "mkdir -p /home/lector/Cloud-API_Deployment/production"

    # - name: "Create a simple file in production"
    #   shell: "touch /home/lector/Cloud-API_Deployment/production/production.html"

    # - name: "Add content to file"
    #   copy: content="<h1>Production Server</h1>" dest="/home/lector/Cloud-API_Deployment/production/production.html"

    # - name: Install pip
    #   apt: name=python-pip state=present

    # - name: Install docker-py
    #   pip: name=docker-py

    - name: Build docker image
      command: docker build -t ov-cloud-api /home/lector/jenkins/workspace/Cloud-API/Cloud-API
      # docker_image:
      #   name: ov-cloud-api
      #   path: ../Cloud-API
      #   state: build^

    - name: Try starting the image
      command: docker start ov-cloud-api
      ignore_errors: yes

    - name: Try running the container
      command: docker run --name ov-cloud-api --env ASPNETCORE_ENVIRONMENT=Development -p 80:8085 ov-cloud-api:latest
      ignore_errors: yes
      # docker_container:
      #   image: ov-cloud-api:latest
      #   path: ../Cloud-API
      #   state: running

    - name: Check if the container is running
      shell: docker ps